name: RSpec Tests

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                ruby-version: ["2.7", "3.0", "3.1", "3.2", "3.3"]
                os: [ubuntu-latest, windows-latest, macos-latest]

        steps:
            - uses: actions/checkout@v4

            - name: Set up Ruby ${{ matrix.ruby-version }}
              uses: ruby/setup-ruby@v1
              with:
                  ruby-version: ${{ matrix.ruby-version }}
                  bundler-cache: true # runs 'bundle install' and caches installed gems automatically

            - name: Run RSpec tests
              run: bundle exec rspec --format documentation

            - name: Upload coverage reports (Ruby 3.3 only)
              if: matrix.ruby-version == '3.3'
              uses: actions/upload-artifact@v3
              with:
                  name: coverage-report
                  path: coverage/
                  retention-days: 30

    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Ruby
              uses: ruby/setup-ruby@v1
              with:
                  ruby-version: "3.3"
                  bundler-cache: true

            - name: Build gem
              run: bundle exec rake build

            - name: Test gem installation
              run: gem install pkg/*.gem

            - name: Test binary executables
              run: |
                  ripple --version
                  worm --version
